### ISSUE TITLE
Actividad 1

### ISSUE THREAD

**Issue by andresPereira** [lilicoronado71/ejerciciosBootcam#1]
Muy bueno el ejercicio.
Tener en cuenta:

- Agregar las buenas practicas en las constantes

Favor realizar las correcciones y realizar un nuevo push

**Comment by lilicoronado71** [comment]
Listo Profe Andrés, ya quedaron los ajustes de acuerdo a sus comentarios y explicación de la clase de hoy.  Muchas gracias.
